const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getState: () => ipcRenderer.invoke('get-state'),
  getManagerState: () => ipcRenderer.invoke('get-manager-state'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  scanBrowsers: () => ipcRenderer.invoke('scan-browsers'),
  validateBrowserRule: (rule) => ipcRenderer.invoke('validate-browser-rule', { rule }),
  scanManager: () => ipcRenderer.invoke('manager-scan'),
  pickExecutable: () => ipcRenderer.invoke('pick-executable'),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  openTarget: (payload) => ipcRenderer.invoke('open-target', payload),
  openChooser: (payload) => ipcRenderer.invoke('open-chooser', payload),
  openProfiles: (payload) => ipcRenderer.invoke('manager-open-profiles', payload),
  hideProfiles: (payload) => ipcRenderer.invoke('manager-hide-profiles', payload),
  deleteProfiles: (payload) => ipcRenderer.invoke('manager-delete-profiles', payload),
  undoDeleteProfiles: (payload) => ipcRenderer.invoke('manager-undo-delete', payload),
  duplicateProfile: (payload) => ipcRenderer.invoke('manager-duplicate-profile', payload),
  renameProfile: (payload) => ipcRenderer.invoke('manager-rename-profile', payload),
  readBookmarks: (payload) => ipcRenderer.invoke('manager-read-bookmarks', payload),
  getProfileFiles: (payload) => ipcRenderer.invoke('manager-profile-files', payload),
  getProfileSize: (payload) => ipcRenderer.invoke('manager-profile-size', payload),
  revealPath: (targetPath) => ipcRenderer.invoke('reveal-path', targetPath),
  closeChooser: () => ipcRenderer.invoke('close-chooser'),
  openSystemSettings: (target) => ipcRenderer.invoke('open-system-settings', target),
  openProfileFolder: (payload) => ipcRenderer.invoke('open-profile-folder', payload),
  showProfileMenu: (payload) => ipcRenderer.invoke('show-profile-menu', payload),
  registerBrowser: () => ipcRenderer.invoke('register-browser'),
  unregisterBrowser: () => ipcRenderer.invoke('unregister-browser'),
  showSettings: () => ipcRenderer.invoke('show-settings'),
  showManager: () => ipcRenderer.invoke('show-manager'),
  showBrowserMenu: (payload) => ipcRenderer.invoke('show-browser-menu', payload),
  showLinkMenu: (payload) => ipcRenderer.invoke('show-link-menu', payload),
  chooserControl: (action) => ipcRenderer.invoke('chooser-control', action),
  setChooserWindowControls: (enabled) => ipcRenderer.invoke('set-chooser-controls', enabled),
  setAssociations: (associations) => ipcRenderer.invoke('set-associations', associations),
  editBrowser: (browserId) => ipcRenderer.invoke('edit-browser', browserId),
  showManagerMenu: (payload) => ipcRenderer.invoke('show-manager-menu', payload),
  setWindowEffect: (effect) => ipcRenderer.invoke('set-window-effect', effect),
  windowControl: (action) => ipcRenderer.invoke('window-control', action),
  resizeChooser: (size) => ipcRenderer.invoke('resize-chooser', size),
  getTheme: () => ipcRenderer.invoke('theme-state'),
  onTheme: (callback) => ipcRenderer.on('theme', (_, data) => callback(data)),
  onInit: (callback) => ipcRenderer.on('init', (_, data) => callback(data)),
  onBlur: (callback) => ipcRenderer.on('blur', () => callback()),
  onManagerMenuAction: (callback) => ipcRenderer.on('manager-menu-action', (_event, data) => callback(data)),
  onProfileMenuAction: (callback) => ipcRenderer.on('profile-menu-action', (_event, data) => callback(data)),
  onBrowserMenuAction: (callback) => ipcRenderer.on('browser-menu-action', (_event, data) => callback(data)),
  onEditBrowser: (callback) => ipcRenderer.on('edit-browser', (_event, data) => callback(data)),
  onLinkMenuAction: (callback) => ipcRenderer.on('link-menu-action', (_event, data) => callback(data))
});
